export const EMAIL = 'joaombn97@gmail.com';
export const GITHUB = 'https://github.com/joao-mbn';
export const LINKEDIN = 'https://linkedin.com/in/joaomarcosbatistanascimento';
export const THESIS = 'http://hdl.handle.net/11422/18995';
export const ETR_OPTIMIZATION_GITHUB = 'https://github.com/joao-mbn/etr-optimization';
export const HOLYDAYS_PRODUCTION = 'https://get-holydays.vercel.app/';
export const HOLYDAYS_GITHUB = 'https://github.com/joao-mbn/holydays';
export const TYPES_HOT_PARSER_NPM = 'https://www.npmjs.com/package/@types/hot-formula-parser';
export const HOT_PARSER_NPM = 'https://www.npmjs.com/package/hot-formula-parser';
export const REACT_EXTRACT_MARKET_PLACE = 'https://marketplace.visualstudio.com/items?itemName=joao-mbn.react-extract';
export const REACT_EXTRACT_GITHUB = 'https://github.com/joao-mbn/react-extract';
export const BIRTH_DATE = new Date(1997, 1, 17);
export const CAREER_START_DATE = new Date(2020, 8, 1);
export const GITHUB_USERNAME = 'joao-mbn';
